### PR TITLE
fix: update go to 1.23.1 for fixing critical CVE issues

### PR DESCRIPTION
**Pull request by derekbit**
Longhorn/longhorn#9898

image

### CODE REVIEW

**Review by innobead — APPROVED** [review]

**Comment by derekbit** [comment]
> Btw what CVE issues are? Are they not fixed in 1.20 patches?

Yes, it is fixed in v1.21.11, but there are HIGH issues. Can we fix them by using go 1.23.1?

image

**Comment by innobead** [comment]
Surely if it can be statically compiled. It should be fine.

**Comment by innobead** [comment]
Will using 1.22 hit this issue? since it has been used in 1.6 and 1.7. I assume the patch should be okay.

**Comment by derekbit** [comment]
> Will using 1.22 hit this issue? since it has been used in 1.6 and 1.7. I assume the patch should be okay.

You are right. 1.22.7 should be okay. Do you want to use 1.22.7 instead?

**Comment by innobead** [comment]
No worries. 1.23 is fine.

**Pull request merged**
